backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "content/products"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    identifier_field: "product_name"
    summary: "{{product_name}} - {{price}}"
    fields:
      - { label: "Product Name", name: "product_name", widget: "string" }
      - { label: "Price", name: "price", widget: "string", hint: "Example: $19.99" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Makeup"
          - "Foundations"
          - "Serum"
          - "Skincare"
          - "Lipsticks"
          - "Hair Care"
      - { label: "Best Seller", name: "best_seller", widget: "boolean", default: false, required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        allow_add: true
        min: 1
        field: { label: "Image", name: "item", widget: "image" }
